name: CI/CD Pipeline
on:
push:
branches:
- main
jobs:
build-and-test:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v4
- name: Build Docker image
# assumes the Dockerfile is in the root (.)
run: docker build -t stylesprint .
- name: Run tests
# assumes a set of unit tests were defined
run: docker run stylesprint python -m unittest discover
deploy:
needs: build-and-test
runs-on: ubuntu-latest
steps:
- name: Checkout code
